### PR TITLE
Fixes and comments

### PR DESCRIPTION
**Pull request by AngainorDev**
In order to run.
Now communicates with the ic but still does not return any coord so far.

### CODE REVIEW

**Comment by kdschlosser** [comment]
I don't know if you caught the forum post where I said you have to initialize the touch driver AFTER the display. This could be what is causing the width and height not to get populated properly.

As far as not getting any coords into LVGL..  you are running the event loop yes?

**Comment by AngainorDev** [comment]
I took this into consideration, as indicated in the top comment as well.

However, my bad, I did call the GT911 constructor after the screen constructor but before the disp_drv was registered (using the older module).
It's now behaving better.
I have a last fix to push to this file and it should be good.

**Comment by kdschlosser** [comment]
yeah I has some pretty dumb typos in that thing didn't I?... Is it working correctly now?

**Comment by AngainorDev** [comment]
Yes, fully working now as is (with the i2c timeout patch mentionned in the comments)

For instance, here is my test program on the Makerfabs board, with previous C display driver:
```
import Makerfabs
import gt911
from machine import Pin, I2C
import lvgl as lv
import lv_utils
import espidf as esp

lv.init()
led = Pin(2, Pin.OUT)
led.on()


disp = Makerfabs.display(de=40, vsync=41, hsync=39, pclk=42, d0=45, d1=48, d2=47, d3=21, d4=14, d5=5, d6=6, d7=7, d8=15, d9=16, d10=4, d11=8, d12=3, d13=46, d14=9, d15=1, width=800, height=480, hsync_polarity=0, hsync_front_porch=8, hsync_pulse_width=4, hsync_back_porch=8, vsync_polarity=0, vsync_front_porch=8, vsync_pulse_width=4, vsync_back_porch=8, pclk_active_neg=1, speed=16000000)
disp.init()

width = 800
height = 480
factor = 8
buf_size = (width * height * lv.color_t.__SIZE__) // factor
disp_buf1 = lv.disp_draw_buf_t()
buf1_1 = esp.heap_caps_malloc(buf_size, esp.MALLOC_CAP.DMA)
disp_buf1.init(buf1_1, None, buf_size // lv.color_t.__SIZE__)

disp_drv = lv.disp_drv_t()
disp_drv.init()
disp_drv.draw_buf = disp_buf1
disp_drv.flush_cb = disp.flush
disp_drv.hor_res = width
disp_drv.ver_res = height
lvd=disp_drv.register()

i2c =  I2C(0, sda=Pin(17), scl=Pin(18), freq=444444)
touch=gt911.GT911(i2c)

scr=lv.obj()
btn=lv.btn(scr)
lbl=lv.label(btn)
lbl.set_text("Press me!")
btn.center()
btn.add_event_cb(lambda event: print('Button clicked!'),lv.EVENT.CLICKED,None)
lv.scr_load(scr)

event_loop = lv_utils.event_loop(asynchronous=False)
```
The coordinates are roughly ok, and the lv event is working right.

**Comment by kdschlosser** [comment]
OK cool deal.

I still have to key up a touchscreen calibration script. The script will store the calibration values in NV memory. I have one that I put together but I have not fully tested it. It's actually pretty simple. I draw a total of 5 buttons. One on each corner and one in the center of the display. I record the x, y values when the screen is touched. I then take those touch coords and subtract them from the actual position of the button that was to be clicked on to get offset values. I then average the offset values. Then I rerun the alignment with the offset values applied and see how close the touches are to the button locations. If they are within whatever percentage of error that is set it accepts that touch input as being valid. If more than 3 of the 5 are not within the percentage of error it will use the touch values that have already been corrected and subtract the new values from that and apply that average to the already existing calibration and it will run the calibration once again. If the calibration runs 3 times and the calibration is not able to be dialed in correctly it will spit out an error stating that the allowed error amount is too small and needs to be widened or there is something wrong with the the digitizer. 

That is what I came up with. it sounds like it should work. The calibration program would run as soon as the touch driver is initialized and no existing calibration data is able to be located in NV memory. I am going to add a counter for the number of touch displays that have been initialized this way if a user has more then one display and those displays are the same brand and model the calibrations will be stored based on the loading order that is defined in the code. Each display will have it's own calibration data as it should. Because the display needs to be loaded before the touch driver it would work out perfect. The loading order for multiple displays would be 

display
touch
display
touch

so when the touch driver collects the display from LVGL the most recent display that has been added will be returned. The touch driver should end up marries to that display when the touch driver is registered with LVGL

**Comment by kdschlosser** [comment]
I did want to mention to you the use of `memoryview` in micropython and why it's so important to use when dealing with any kind of communications on the ESP.

as you already know the amount of resources is very limited on the ESP. If you are using any form of communications whether it be WiFi, BT or I2C, basically anything you want to keep the amount of resources used in check. The other thing you have to concern yourself with is memory fragmentation from making a lot of small containers. As an example you have the touch interface, You have seen what the output is when you move your finger. It spits out coords like it's no body's business. If you create a data buffer in the functions that handle the processing of those coords each time the function is run x bytes of memory gets allocated for the buffer. In this case it is 6 bytes. unless the GC is run often you will end up with memory fragmentation. which is where there is something stored in memory but it is not in use. Memory allocation is not contiguous things get stuck in there all over the place. in the example of 6 bytes You could have 500K free but end up with a memory allocation error if there isn't 6 bytes that are contiguous for the buffer. So when we do is we allocate a buffer once and only once so multiple allocations don't need to occur keeping the memory from getting fragmented.

Now here is the twist to it.

If you allocate 6 bytes in a bytearray if you slice that bytearray a copy is made. If you pass the buffer in a function call a copy is made. That copy is mutable but it is still a copy. when a copy gets made allocation of memory occurs and fragmentation happens. So how we stop that form happening is using memoryview. what you do is create the buffer and then create another variable that wraps the buffer in memoryview you assign the bytes like you would as normal to the buffer but when you want to pass the buffer to a function you pass the memoryview object instead, or even a sliced memory view. This passes a memory pointer instead of making a copy of the buffer. No memory allocation occurs when you do this.

In ESP programming any time you need a large data buffer that is going to be used over and over again it is always best to initialize it at the very beginning of your program. That is why it is best to initialize the display first and foremost because it has a HUGE buffer that it uses. This ensures that you will get the contiguous memory needed for the buffer allocation,


Here is an example of what I am talking about

```python
class GT911(_touch_base.TouchBase):

    def __init__(
        self,
        i2c,
        invert_x: bool = False,
        invert_y: bool = False,
        swap_xy: bool = False,
    ):
        self.i2c = i2c
        self.data_buf = bytearray(6)
        self.mv = memoryview(self.data_buf)

        super().__init__(invert_x=invert_x, invert_y=invert_y, swap_xy=swap_xy)

    def init(self):
        config = bytearray([
            (GT911_REG_CONFIG_DATA & 0xFF00) >> 8,
            GT911_REG_CONFIG_DATA & 0xFF,
            0x81,
            self.width & 0x00FF,
            (self.width >> 8) & 0x00FF,
            self.height & 0x00FF,
            (self.height >> 8) & 0x00FF,
            1,
            (int(self.invert_y) << 7) |
            (int(self.invert_x) << 6) |
            (int(self.swap_xy) << 3) |
            (1 << 2),
            0x20, 0x01, 0x08, 0x28, 0x05, 0x50,  # 0x8047 - 0x8053
            0x3C, 0x0F, 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00,  # 0x8054 - 0x8060
            0x00, 0x89, 0x2A, 0x0B, 0x2D, 0x2B, 0x0F, 0x0A, 0x00, 0x00, 0x01,
            0xA9, 0x03,  # 0x8061 - 0x806D
            0x2D, 0x00, 0x01, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x21,  # 0x806E - 0x807A
            0x59, 0x94, 0xC5, 0x02, 0x07, 0x00, 0x00, 0x04, 0x93, 0x24, 0x00,
            0x7D, 0x2C,  # 0x807B - 0x8087
            0x00, 0x6B, 0x36, 0x00, 0x5D, 0x42, 0x00, 0x53, 0x50, 0x00, 0x53,
            0x00, 0x00,  # 0x8088 - 0x8094
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00,  # 0x8095 - 0x80A1
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00,  # 0x80A2 - 0x80AD
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x04, 0x06,
            0x08, 0x0A,  # 0x80AE - 0x80BA
            0x0C, 0x0E, 0x10, 0x12, 0x14, 0x16, 0xFF, 0xFF, 0xFF, 0x00, 0x00,
            0x00, 0x00,  # 0x80BB - 0x80C7
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00,  # 0x80C8 - 0x80D4
            0x02, 0x04, 0x06, 0x08, 0x0A, 0x0F, 0x10, 0x12, 0x16, 0x18, 0x1C,
            0x1D, 0x1E,  # 0x80D5 - 0x80E1
            0x1F, 0x20, 0x21, 0x22, 0x24, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
            0xFF, 0x00,  # 0x80E2 - 0x80EE
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00,  # 0x80EF - 0x80FB
            0x00, 0x00, 0xD6, 0x01  # 0x80FC - 0x8100
        ])

        config[184] = 0
        
        for i in range(184):
            config[184] += config[i]
        
        config[184] = (~config[184]) + 1
                
        # Get product ID
        print('Touch product id:', self.product_id)
        print('Touch firmware:', self.firmware)

        self.i2c.writeto(GT911_I2C_SLAVE_ADDR, config)
        self.set_command_register(0x00)

    def _get_coords(self):
        status = self.status

        if (status & 0x80) != 0:
            coord_num = status & 0x0F
            if coord_num != 0:
                coord_x = []
                coord_y = []
                for i in range(coord_num):
                    self.data_buf[0] = (
                        ((GT911_POINT1_X_ADDR + (i * 8)) & 0xFF00) >> 8
                    )
                    self.data_buf[1] = (GT911_POINT1_X_ADDR + (i * 8)) & 0xFF
                    self.i2c.writeto(GT911_I2C_SLAVE_ADDR, self.mv[:2])

                    self.i2c.readfrom_into(GT911_I2C_SLAVE_ADDR, self.mv[:6])

                    x = self.data_buf[0]
                    y = self.data_buf[2]
                    x |= (self.data_buf[1] << 8)
                    y |= (self.data_buf[3] << 8)

                    coord_x.append(x)
                    coord_y.append(y)

                x = int(sum(coord_x) / len(coord_x))
                y = int(sum(coord_y) / len(coord_y))

                if self.swap_xy:
                    x, y = y, x

                if self.invert_x:
                    x = self.width - x

                if self.invert_y:
                    y = self.height - y

                if y < 0:
                    y += abs(y)

                self.status = 0
                return x, y

            self.status = 0

    def set_command_register(self, command):
        self.data_buf[0] = (GT911_REG_COMMAND & 0xFF00) >> 8
        self.data_buf[1] = GT911_REG_COMMAND & 0xFF
        self.data_buf[2] = command

        self.i2c.writeto(GT911_I2C_SLAVE_ADDR, self.mv[:3])

    @property
    def product_id(self):
        self.data_buf[0] = (GT911_REG_ID & 0xFF00) >> 8
        self.data_buf[1] = GT911_REG_ID & 0xFF
        self.i2c.writeto(GT911_I2C_SLAVE_ADDR, self.mv[:2])
        self.i2c.readfrom_into(GT911_I2C_SLAVE_ADDR, self.mv[:4])

        buf = bytearray([self.data_buf[3], self.data_buf[2], self.data_buf[1], self.data_buf[0]])
        return buf.decode('utf-8')

    @property
    def firmware(self):
        self.data_buf[0] = (GT911_REG_FW_VER & 0xFF00) >> 8
        self.data_buf = GT911_REG_FW_VER & 0xFF

        self.i2c.writeto(GT911_I2C_SLAVE_ADDR, self.mv[:2])
        self.i2c.readfrom_into(GT911_I2C_SLAVE_ADDR, self.mv[:2])

        return self.data_buf[1] << 8 | self.data_buf[0]

    @property
    def status(self):
        self.data_buf[0] = (GT911_READ_COORD_ADDR & 0xFF00) >> 8
        self.data_buf[1] = GT911_READ_COORD_ADDR & 0xFF

        self.i2c.writeto(GT911_I2C_SLAVE_ADDR, self.mv[:2])

        self.i2c.readfrom_into(GT911_I2C_SLAVE_ADDR, self.mv[:1])
        return self.data_buf[0]
        
    @status.setter
    def status(self, value):
        self.data_buf[0] = (GT911_READ_COORD_ADDR & 0xFF00) >> 8
        self.data_buf[1] = GT911_READ_COORD_ADDR & 0xFF
        self.data_buf[2] = value
        self.i2c.writeto(GT911_I2C_SLAVE_ADDR, self.mv[:3])
```

**Comment by kdschlosser** [comment]
Just to let you know that the code above is going to be what the final looks like. I am going to merge your PR so you get the credit for making the changes to the GT911 driver and then I am going to apply the above code to those changes. I don't want to skirt giving credit where it is due. You have helped out a HUGE amount with all of this so far and I want to make sure that any changes you make you get credit for.

**Comment by AngainorDev** [comment]
Thanks, and roger that!

Yes, I'm familiar with memoryview, I already used them extensively in other contexts.
I also had in mind to further optimize the driver in a next step.
"premature optimization is the root of all evil" ;)

Great Job, eager to have a clean framework soon!

**Comment by kdschlosser** [comment]
I think we are definitely making really good headway on this. I am happy that your display is not sitting in a drawer not being used because of lack of support in LVGL for it. That is the exact reason why I ended up spending the time on learning how to add to LVGL. I had a need to fill and there was nothing that was going to fill it. I also wanted to make it easier to update the program code over WiFi so that meant using MicroPython

**Comment by kdschlosser** [comment]
I did want to mention. If you update your version of micropython to the master branch on github you will not need to set that define in mpconfigboard. The problem has been corrected but there is no release yet with the fix added to it. Since the S3  SOC was just added to the boards list for the ESP32 port you should be running the master branch of micropython anywho so setting that macro should not need to be done. 

You should be using espidf version 4.4.4

**Pull request merged**
